### ISSUE TITLE
MPRIS Issue (Specifically with Sunamu) 

### ISSUE THREAD

**Issue by KorbsStudio** [Mastermindzh/tidal-hifi#140]
An issue was created in Sunamu's repo yesterday: https://github.com/NyaomiDEV/Sunamu/issues/16

The Sunamu app detects the currently playing music player, which is my case was "TIDAL HiFI". Sunamu was only showing the album cover, yet nothing else changed.

According to the developer of Sunamu, your implementation on MPRIS "...is non-compliant or lacking...". 

Rest of what the developer of Sunamu had to say: 
> Didn't know Tidal Hi-Fi got a port to Linux, assuming that's community based it may as well be that their implementation is non-compliant or lacking, especially since Sunamu relies on proper event firing from the player's end while other MPRIS implementations sacrifice performance for reliability in worst-case scenarios via manual polling. I could also implement that, but I would prefer (and everyone wins) if this issue is taken to their issue tracker so that they can see if their implementation is strictly following the spec. 

> Doing an MPRIS2 implementation is straightforward, but doing it well enough is pain in the butt, especially in Electron.

https://user-images.githubusercontent.com/51213244/167315192-4bf4fee0-6567-4758-85f8-9a022710196f.mp4

**Comment by Mar0xy** [comment]
tidal-hifi uses the [mpris-service module](https://www.npmjs.com/package/mpris-service) it gets initialized in the preload.js file on line 436 https://github.com/Mastermindzh/tidal-hifi/blob/374f3da74005b7b537b760feff9a8931f4c752e3/src/preload.js#L436

While the data gets set in preload.js from line 292 to 312
https://github.com/Mastermindzh/tidal-hifi/blob/374f3da74005b7b537b760feff9a8931f4c752e3/src/preload.js#L292-L312

the only thing similar to this issue would be https://github.com/Mastermindzh/tidal-hifi/issues/122 but his issue got fixed with the update to Electron 15 so it seems to be more of a issue with Sunamu in this case as it works otherwise fine.

Though this is only my opinion I don't know how Mastermindzh sees it

**Comment by Mastermindzh** [comment]
I agree with @Mar0xy,

We simply use the default npm package which has been tested with the major use cases (e.g gnome/kde/etc media centers).
There are two ways forward i.m.o:

- Either @KorbsStudio or someone else finds (or asks) the "required" events that Sunamu listens to and I can try to add them
- We will have to wait until I have a lot of free time again (probably a vacation in a month or so) so I can do some research

Either way, neither option guarantees result, we can only try 😄
