### ISSUE TITLE
Automatic muting sometimes not working

### ISSUE THREAD

**Issue by vincens2005** [Mastermindzh/tidal-hifi#141]
sometimes, the mute button is automatically clicked, but the volume does not turn off. The icon toggles, implying that the sound is muted, but it still plays.

**Comment by Mastermindzh** [comment]
Mmm that is weird 🤔 
We don't actually control any volume/audio, that is all done by tidal.
Tidal-hifi just clicks a few buttons for all the actions.

Is there any more context? Maybe stuff like:
- Only a certain machine?
- Only a certain artist?
- What happens on "unmute"?
- Can you toggle mute yourself?
- What happens if tidal-hifi mutes, and then you click on unmute?

**Comment by vincens2005** [comment]
When I unmute, it will unmute if the song is playing, or immediately remute (and work properly) if it's an ad. Toggling mute manually always works, and it appears to be artist-agnostic. I've only got one machine, so I can't say if it's just an edge case having to do with my setup. I suspect it might have to do with window focus, but I'm not sure

**Comment by Mastermindzh** [comment]
I've added a few of my favourite artists to my ignore list for today.
Haven't encountered any issues before but it might show up eventually.

Haven't been able to replicate it yet though.
