### ISSUE TITLE
Artist name not displaying in media player 

### ISSUE THREAD

**Issue by dspacejs** [Mastermindzh/tidal-hifi#15]
No artist is showing in the media player for every song:

![Media player](https://user-images.githubusercontent.com/9282837/89966037-661e9080-dc8d-11ea-8313-256e83cacfad.png)

I'm on Ubuntu 20.04.1 LTS with Gnome 3.36.3

**Comment by Mastermindzh** [comment]
What version are you using?
Which artist are you listening to?

I just checked and for me, they still show up, so the UI hasn't changed (which is where we fetch data from).

Might be the artist name? Idk, please give me some extra info and I'll surely have a look!

**Comment by dspacejs** [comment]
@Mastermindzh how do I check the version? I just installed the .deb package, I can't remember what version it was. Can't find anywhere in the app that specifies the version either, or any `--version` command for `tidal-hifi` on the command line.

It doesn't show for me for any music at all. So I don't think it depends on the artist.

Btw, the album art isn't showing in this media player either.

**Comment by Mastermindzh** [comment]
.deb is the version that I needed :)
The app is straight from Tidal so it has a version embedded somewhere but it gives the Tidal app version.

I'll be more clear in what I mean next time.
I now understand it's not a notification but a media player, I haven't added media player API's as of yet. There have been 2 requests so far (counting yours).

Can you please verify whether the notifications (settings -> enable notifications) show the artist name? If they do I know none of the current code has broken due to Tidal updates.

I'll add a ticket for playback API support and see what I can do with it ;)

**Comment by Mastermindzh** [comment]
I have created an issue for this in the dev board: https://github.com/Mastermindzh/tidal-hifi/issues/17

I will keep it open until I gather the info I requested from you and after that I'll track progress on the other issue. Feel free to add your details on issue #17 if you want :)

Thanks for the feedback!

**Comment by dspacejs** [comment]
@Mastermindzh thanks, here's what shows when notifications are turned on:

![Screenshot from 2020-08-21 15-07-48](https://user-images.githubusercontent.com/9282837/90856080-4ccdc080-e3c0-11ea-9b60-c083a75b9322.png)

It shows both the media player + the notification

**Comment by Mastermindzh** [comment]
Thanks. I'll try to have a look at media APIs this weekend. It seems the notification still does what it was supposed to so it's just the API integration that is missing.

**Comment by dspacejs** [comment]
@Mastermindzh would be great to just use the media player, instead of both

**Comment by Mastermindzh** [comment]
The notification API works on all platforms. The media player APIs are not the same across all platforms ;)

Still, I'll see what I can do for the media player API (at least in Linux..) once I get some time to work on it.

**Comment by Mastermindzh** [comment]
So... I'm busy (as I'm sure we all are)...
but... I just dedicated some time in my weekend to go over this feature (as well as fix the security bug in a dependency).

I'll keep you up-to-date.

**Comment by dspacejs** [comment]
@Mastermindzh much appreciated

**Comment by Mastermindzh** [comment]
Caught me in the act of setting up the test environment ;)

![image](https://user-images.githubusercontent.com/4190290/92324163-49346d80-f03f-11ea-8ad2-2b276af0f4ef.png)

**Comment by Mastermindzh** [comment]
Hey @dspacejs ,

I can't seem to find the media control you are talking about. How do I get it on the fresh install with Gnome? (sorry, not familiar with gnome)

**Comment by Mastermindzh** [comment]
Ok nvm.. it was hiding in the clock for some bizarre reason :)

**Comment by Mastermindzh** [comment]
![image](https://user-images.githubusercontent.com/4190290/92325250-5a827780-f049-11ea-8767-237d1cb14aea.png)

Bit weird still. I now have 2 of them, on both of them the buttons work and the first one seems to be the one I can control with code but I have no idea where the second one comes from, I guess it's trying to automatically find stuff

**Comment by Mastermindzh** [comment]
![image](https://user-images.githubusercontent.com/4190290/92325320-d67cbf80-f049-11ea-859a-bcb61dbdcce7.png)

Image shows correctly but still can't get rid of the second one.

**Comment by Mastermindzh** [comment]
Don't think I can actually control the second one in any way

**Comment by dspacejs** [comment]
> Bit weird still. I now have 2 of them, on both of them the buttons work and the first one seems to be the one I can control with code but I have no idea where the second one comes from, I guess it's trying to automatically find stuff

@Mastermindzh I got rid of the second one by turning off the "Notifications" setting in the app. It seems like the app is creating a second media player instead of using the native one in Ubuntu.

**Comment by Mastermindzh** [comment]
I'm not sure we're talking about the same thing actually, In the screenshot above I have notifications turned off as well.

I'm using the dbus interface through mpris, I did indeed "create" a player because tidal-hifi didn't have one before. mpris doesn't seem to give a hook into existing players either (if it was spawned by gnome me having access to it in code would also be a pretty big security issue).

My best guess is that gnome is actually just creating a player because it finds a website with something playing on it. Also tested it on KDE and it seems to work fine there, was going to test cinnamon later.

Have to wait till the build error is fixed (it's throwing a 403 now... idk why yet) but I fixed all the other stuff and the player is now working as expected. As soon as the builds are fixed I'll provide a .deb for you to try

**Comment by dspacejs** [comment]
@Mastermindzh that's strange, only a single player is showing for me. The only time it has two players is when the notifications setting is turned on. So I don't know how to provide instructions for how to reproduce what I'm experiencing. 

> My best guess is that gnome is actually just creating a player because it finds a website with something playing on it

Hmm, probably not. Because electron isn't really considered a web application. Isn't the TIDAL app just embedded inside the electron app? If so then I'm assuming it wouldn't have any way to detect this.

**Comment by Mastermindzh** [comment]
Electron is an instance of chromium. Chromium uses the system API to play music so any system-wide code can detect it :) (I used to have a similar play widget on my i3 session which did exactly that)

Did you test the version from the branch? Or the released .deb? Because only the version in the actual branch creates 2 for me :smile: 

Anyhow, I'll do tests on cinnamon and some other DE's this weekend. If it looks normal on most of them I can include the code with a toggle :smile:

**Comment by dspacejs** [comment]
@Mastermindzh hmm, not sure what version I installed, it was a while ago. How do I check?

**Comment by Mastermindzh** [comment]
Would be an older one without this code then ;)
Haven't been able to do a release because of the 403.

I'll do some more work on the 403 in the weekend and I'll create the toggle for this (beta) feature ;)

**Comment by Mastermindzh** [comment]
The 403 is caused by adding mpris-service (the javascript module which talks to mpris) as a dependency to the project:

https://github.com/Mastermindzh/tidal-hifi/actions/runs/287626373

For now, I've removed the dependency meaning the player is never instantiated.
With all the other fixes it does work on GNOME now but it's not using mpris as you can see below.

![image](https://user-images.githubusercontent.com/4190290/95011447-0c08ce80-0631-11eb-8023-301bec558dce.png)

To fix the image I am pretty sure we need mpris-service so that won't happen unless someone can figure out the entire 403 situation.

**Comment by Mastermindzh** [comment]
It's got something to do with the dbus package. I'll submit an issue there but who knows...

**Comment by Mastermindzh** [comment]
Fixed in [v1.1.0](https://github.com/Mastermindzh/tidal-hifi/releases/tag/1.1.0).
Please open a new issue if an issue arrives.
