### ISSUE TITLE
Blurry UI in Wayland with fractional scaling

### ISSUE THREAD

**Issue by pjautuvas** [Mastermindzh/tidal-hifi#157]
Please add Wayland support. The application is too blurry on a laptop with Gnome 42 Wayland session and 150% scaling.

**Comment by Mastermindzh** [comment]
Please add some details about your environment and some pictures.
I haven't had any problems on wayland with 100% scaling so it might just be a scaling issue.

**Comment by gordallott** [comment]
this is a pretty common problem with fractional scaling and wayland. I'm not sure what else can be added to the issue. using fractional scaling and a non integer scaling will result in blurry visuals because it basically just upscales the 100% app to 150%. 

you can "fix" this by running electron in wayland mode 
`--verbose --log=TRACE --enable-features=UseOzonePlatform --ozone-platform=wayland`

but you lose window decorations doing so, aside from that it seems to work okay? I don't know enough about this to say what should be done about the window decorations

**Comment by gordallott** [comment]
update, adding `--enable-features=WaylandWindowDecorations` kind of gets you somewhere, but the menubar draws all over the electron window decorators

**Comment by nrbeaton** [comment]
I am having this issue with Fedora (Gnome) on Wayland.

Adding the `--ozone-platform-hint=auto` and `--enable-features=WaylandWindowDecorations` flags fix the issues with Chromium and VSCodium (both flatpak versions) but have no effect on Tidal-HiFi.

Is it something to do with the version of Electron?

**Comment by Nyabinary** [comment]
I think ozone platform being set to auto is a good first step for this issue
