### ISSUE TITLE
App always requests a default-url-handler-scheme change on  start

### ISSUE THREAD

**Issue by kbasaran** [Mastermindzh/tidal-hifi#172]
Hello,
Since I switched to version 4.2.0, each time I start the app I get a pop-up asking: 

> Allow snap "tidal-hifi" to change "default-url-scheme-handler" subproperty "tidal" to "tidal-hifi_tidal-hifi.desktop" ?

I answer yes, but it will be asked again on next start-up of the app.
I have a snap install on Ubuntu 22.04.1.
Thank you for your work and hope you keep it up,
Kerem

**Comment by kbasaran** [comment]
This caused another problem.. Tidal-hifi became default application for something it shouldn't. On the Dropbox app, when I choose "Show my Dropbox folder on web", it launches Tidal-hifi instead of my browser to show this location.

**Comment by Mastermindzh** [comment]
I have no idea why snap would ask this all the time (not too familiar with snaps).

The other problem is weird, since snap clearly **knows** that the subproperty is tidal 🤔, I don't think dropbox would embed any tidal links...

I'll have a look when I have time but I'm completely unfamiliar with snap :/

**Comment by MrWhammy** [comment]
Looking at a [pull request](https://github.com/ytmdesktop/ytmdesktop/pull/639/files) from a similar issue on another repo, I think the fix can be just as simple [here](https://github.com/Mastermindzh/tidal-hifi/blob/master/src/main.js#L126), but I'm completely unfamiliar as well.

**Comment by Mastermindzh** [comment]
Ah.... that would make sense... I thought it would do that automatically.

I can probably make that happen over the weekend! (though you're free to submit a PR as well, I think you are spot on with the answer 😄 )

Thanks for debugging! I was really thinking it was a snap issue but it's probably a system-wide thing and it's just that snap ENFORCES you to click accept (because of their security principles)

Really nice find!

**Comment by Mastermindzh** [comment]
Fixed in [4.3.1](https://github.com/Mastermindzh/tidal-hifi/releases/tag/4.3.1) by @MrWhammy
