### ISSUE TITLE
Why not skip tracks instead of muting them automatically?

### ISSUE THREAD

**Issue by BlueManCZ** [Mastermindzh/tidal-hifi#175]
There is a feature to mute particular artists automatically and it works as expected, but why not take this even further and skip those tracks automatically for seamless playback?

A naive approach would be to select the "Next" button and trigger the click event on it:

```js
$("button[data-type='button__skip-next']").click()
```

But I guess the "next" functionality is already implemented somewhere in the code, so it could probably be called, right?

https://github.com/Mastermindzh/tidal-hifi/blob/d161a68c95eb78320f7f09254dfe1446a7695000/src/scripts/express.js#L43

https://github.com/Mastermindzh/tidal-hifi/blob/d161a68c95eb78320f7f09254dfe1446a7695000/src/preload.js#L20

**Comment by Mastermindzh** [comment]
The "Mute" functionality was originally a request to automatically mute ads (which are, apparently on a 'free' tier in some countries) which can't be skipped.

Adding another functionality that can skip songs should be a problem, but in order to serve the people that don't want to hear the ads we have to keep the mute as well :) 

You are correct that there is reusablecode as well. It just isn't in the express.js file.
In the `preload.js` file there is an object (`elements`) with a `click` method.

You can call it from anywhere in the preload like so:
`elements.click("next")`
and it will click the next button (which you identified with your second link to the code.
