### ISSUE TITLE
Remember window size when reopening application

### ISSUE THREAD

**Issue by dspacejs** [Mastermindzh/tidal-hifi#20]
I always maximise the window size, but when restarting the application it always starts in a small window. It would be nice if it remembered the previous size of the window when the app was last used and automatically expanded to this.

## Envionment

Ubuntu 20.04.1 LTS

Gnome 3.36.3

**Comment by Mastermindzh** [comment]
That's because of lines [37-38](https://github.com/Mastermindzh/tidal-hifi/blob/master/src/main.js#L37-L38)

I'm already storing the size in the store on lines [63-67](https://github.com/Mastermindzh/tidal-hifi/blob/master/src/main.js#L63-L67)

So the fix would simply be to use what is in the store before the app starts or fall back to the default if the store is empty.

I can get on it this weekend, but again, with electron-builder failing to download dependencies I can't exactly release a new version (because the .deb etc won't build). I'll fix it regardless and ship you instructions to test both this and the player integration, ok?

**Comment by dspacejs** [comment]
@Mastermindzh sure, thanks. Happy to test it for you.

**Comment by Mastermindzh** [comment]
Fixed in [v1.1.0](https://github.com/Mastermindzh/tidal-hifi/releases/tag/1.1.0).
Please open a new issue if an issue arrives.
