### ISSUE TITLE
tidal-hifi stops playing music after ~20s on Windows due to DRM issues (I think)

### ISSUE THREAD

**Issue by em-et** [Mastermindzh/tidal-hifi#233]
When I try to play any song using the tidal-hifi app on Windows (used MSI installer), both in normal and in Hi-Fi quality, it stops after ~20 seconds.
Opening up the developer tools on the app, it shows that fetching `https://listen.tidal.com/v1/drm/licenses/widevine?token=xxxxxxxxxxxxxxxx` returns a 400 error with this response from the server:
`{"status":400,"subStatus":999,"userMessage":"DRM request failed."}`.
The error code it shows me on screen is:
`There was an unexpected error. Try again later. (S6007)`
The error code `S6007` seems to be related to DRM issues, when I looked it up.
On Linux, things seem to be just fine, everything works as expected.

**Comment by Mastermindzh** [comment]
Hey @em-et,

This product is developed primarily for Linux as Windows has it's own (free) client.
In this particular case I have no idea what we would be able to do to get the DRM working on Windows, sorry.

**Comment by L-m-b** [comment]
I understand this issue is closed due to windows having its own client, pretty sure its up to electron to have DRM working to some regard, had the same drm issue on some versions of firefox recently when tidal introduced their own drm keys.

Whole use case for your app is that the usual windows app has been inconvenient sometimes randomly logs me out takes a couple goes to open for whatever reason and spends a lot longer buffering.
don't know if you need to update something electron side for windows but it would be awesome if it worked.
