### ISSUE TITLE
delete key searches for "Delete"

### ISSUE THREAD

**Issue by gerbrent** [Mastermindzh/tidal-hifi#274]
When on any section of the Tidal interface - playlist view, Home, Albums, etc - hitting `delete ` on the keyboard auto-fills the search field with "Delete":

![tidal - delete searched for  delete](https://github.com/Mastermindzh/tidal-hifi/assets/7018928/f3f4de2f-e063-433e-a845-20a6859d9a1d)

Attempted the same in the Tidal web interface via browser (i.e. outside of tidal-hifi) and can not reproduce there.

openSUSE Tumbleweed KDE Plasma - installed via flatpak (ver. 5.6.0)

**Comment by Mastermindzh** [comment]
Hey,

Weird! Haven't seen that happen before!
I don't think we're watching for any delete key but this is certainly incorrect behavior.

Can't help but notice that on the playlist view you've got several items selected when you hit delete, I tried that on [listen.tidal.com](https://listen.tidal.com) and it didn't do **anything** so I'm not sure what behaviour you were after.

Will mark as bug and investigate!

**Comment by gerbrent** [comment]
ooo, fun, a unique find!

The behaviour I was attempting here was "delete all these items from this playlist" and since I'm relatively new to Tidal, was poking around with what's possible re keyboard interface.

Turns out the highlighting is inconsequential to this particular bug - I tested it! - but figure showing it in gif walkthrough might be interesting (turns out it was!).

Yes, indeed, fascinatingly incorrect behaviour, took me a moment to realize what had occurred!


I tried the highlighting on [listen.tidal.com](https://listen.tidal.com/) too, after finding this, to distinguish between Tidal-HiFi bug and Tidal bug, so glad we came to the same conclusion. 

Anyhow, hopefully this is a fun one to seek out - enjoy and good luck!!
(and, of course, thanks for this project everyone!)

**Comment by Mastermindzh** [comment]
I did some research and it turns out this is a bug with Tidal itself, unfortunately.
If you open [listen.tidal.com](http://listen.tidal.com) in Chrome and hit "delete" it will also populate the search field :/
However, if there's text in the field already and you use delete it will successfully remove the next character.

I'll see what I can do. Maybe I can add a listener on delete and check for the length of the search field, if it's 0 prevent the action. Idk though.

I will also send this thread to bugreport@tidal.com

https://github.com/Mastermindzh/tidal-hifi/assets/4190290/ae97424c-415b-4adf-95c2-8de9ad2fbec9

**Comment by Mastermindzh** [comment]
Made the report:
[tidal-bugreport.pdf](https://github.com/Mastermindzh/tidal-hifi/files/12387770/tidal-bugreport.pdf)

**Comment by Mastermindzh** [comment]
No (easy) way for us to fix this tbh.
I am intercepting pretty much every keydown/up interceptor now just to handle this edge case,

Will have to wait until TIDAL fixes it I'm afraid :'(

Sorry!
