### ISSUE TITLE
feature - list version number in About

### ISSUE THREAD

**Issue by gerbrent** [Mastermindzh/tidal-hifi#275]
Currently the `About` menu items pop-up does not report the tidal-hifi version number, as is fairly customary and helpful esp when reporting bugs 🐞 .  

Could consider adding the version number to the About pop-up.

![image](https://github.com/Mastermindzh/tidal-hifi/assets/7018928/c32013db-24f3-45dc-995a-9e13a57e8406)

**Comment by Mar0xy** [comment]
I think the about section should be generally overhauled to fix mistakes in the sentence, add a small contributor list, show the version/build and also to link to the GitHub page

**Comment by Mastermindzh** [comment]
I agree with the redesign but there are no grammatical or spelling errors in the current sentence. 🤔

**Comment by Mar0xy** [comment]
> I agree with the redesign but there are no grammatical or spelling errors in the current sentence. 🤔

I meant something like the `'` after castlabs as it always make it seem like there is missing something after the `'`

**Comment by gerbrent** [comment]
Could suggest:

> ...it uses the Castalabs version of Electron...

**Comment by Mastermindzh** [comment]
Hehe, this is actually 1 of the more debated grammatical subjects out there (top-rank shared with the Oxford comma iirc).

The `'` after `Castlabs` is actually correct and the suggestion given by @gerbrent  is unfortunately grammatically incorrect  😄.
Since we are using their specific electron version we have to use the "possessive form" for the noun `Castlabs`.
Rules around the possessive form are simple but can be deceiving when the noun is singular (like a name) but ends with an s. Since it's a name (and thus singular) you can add either `'` or `'s` with `'` being more common according to the [Cambridge Dictionary](https://dictionary.cambridge.org/grammar/british-grammar/possession-john-s-car-a-friend-of-mine).

But... there is also a common exception for names that contain a plural noun (e.g. `labs` in `castlabs`) in most British, and some American... like CMOS), style guides that require you to only add the apostrophe and not the s, forming: `Castlabs'` or `American airlines'`. 

Those are the reasons I have gone with a single apostrophe behind Castlabs 😄, I was taught that way.
But, if it is bothering both of you we can throw the style guide out of the window and use the, less common but grammatically still correct, `Castlabs's`.


PS: And yes... I am a bit of a grammar nerd. LOL

PPS: I can work on Tidal Hi-Fi later tonight or maybe tomorrow, let me know if either of you wants to work on the "about" screen redesign please so that we don't accidentally work on the same thing 😄.

**Comment by Mar0xy** [comment]
> I can work on Tidal Hi-Fi later tonight or maybe tomorrow, let me know if either of you wants to work on the "about" screen redesign please so that we don't accidentally work on the same thing

I am not good at doing design related stuff so I will leave it up to you as I just gave baseline ideas :laughing:

**Comment by Mastermindzh** [comment]
Got like 90% of the new shed and carport lighting install done today so I'll definitely have time tomorrow.

I'll see what I can do on the design, not my strongest suite either 😂

**Comment by Mastermindzh** [comment]
![image](https://github.com/Mastermindzh/tidal-hifi/assets/4190290/3a7e59e6-1559-4e85-b7b8-bd31aa9697b2)

Current design :)
