### ISSUE TITLE
Feature - create option for scrobbling delay for Listenbrainz and other scrobbling services

### ISSUE THREAD

**Issue by LilithHellhound** [Mastermindzh/tidal-hifi#277]
When you try to skip through music in TIDAL, when connected to Listenbrainz, it will log every single song you listen to, even if it's for 1 second. I think an option to set a delay would be an extremely useful option.

**Comment by Mastermindzh** [comment]
Can add this in the next release.

**Comment by ThunderFun** [comment]
I'm experiencing some issues with the scrobbler. Despite setting the delay to 60 seconds, songs are still being scrobbled even if I only listen to them for 10 seconds. Additionally, the 'listening now' feature seems to be affected by the delay, rather than just delaying the logging of the song.

For comparison, other ListenBrainz scrobblers like Strawberry have specific rules in place: "Songs are scrobbled if they have valid metadata and are longer than 30 seconds, have been playing for at least half its duration or for 4 minutes (whichever occurs earlier)"

If I play a song on Strawberry for example, it immediately shows up as 'Listening now' on ListenBrainz, but it doesn't actually get logged until the specified conditions are met.
