### ISSUE TITLE
JavaScript error on pause

### ISSUE THREAD

**Issue by aedalzotto** [Mastermindzh/tidal-hifi#340]
Whenever I play or pause the playback, I get "A Javascript error occurred in the main process."
This is annoying as the error window pops up, and I can't play the song until I close it.
This can happen as well when passing to the next track multiple times.

I've tried to build the package from source, but the error still persists.

![image](https://github.com/Mastermindzh/tidal-hifi/assets/12283310/84279fcf-5772-4dce-acb3-738bbc0f095b)

**Comment by Mastermindzh** [comment]
I've been working on TIDAL Hi-Fi today and have encountered no such issues, unfortunately.
Seems your TIDAL doesn't have an STDOUT connected, how are you launching it?

**Comment by niraami** [comment]
I'm running into the same issue recently, latest release 5.8.0 via Arch `tidal-hifi-bin` package.
To reproduce, launch tidal from a terminal, and make it a background process (also disown if necessary), like so:
```bash
tidal-hifi &
# or
tidal-hifi &!
```
It should function normally, up until the moment you close the terminal, then the errors will appear on each pause/unpause.
The only logs that appear when doing so (while terminal is still open), are these:
```
Started preventing app suspension with id: 0 
Released inhibitor with id: 0 
Started preventing app suspension with id: 1
```

**Comment by Mastermindzh** [comment]
Yeah, now that makes sense. 

When you disown and then kill the parent terminal you are removing the STDOUT target that was set by launching tidal-hifi in the first place (the parent terminal).
Or, simply put: you're intentionally removing the STDOUT and **not** redirecting it.

It makes sense that tidal-hifi can't write to the output anymore by then and starts throwing errors as the STDOUT is required.
Instead of disowning and then not redirecting the output you should disown with a redirected STDOUT:

```sh
tidal-hifi >/dev/null &
```

That will run it in the background and redirect its STDOUT into the garbage can.
The alternative would be hiding logs/errors away with a try catch but that seems nasty.

**Comment by niraami** [comment]
`.desktop` files exhibit this same behavior, losing stdout is a normal part of a GUI application. Same goes for flatpak. I don't of in which way you are launching Tidal that you don't receive these errors.
I don't believe requiring every possible way of launching Tidal to use pipe to keep alive STDOUT to be correct.

I also don't understand see how suppressing an exception about lack of stdout could be nasty.. you're not checking if stdout exists, so of course it causes an exception. Disabling logging on the first instance of a write error would probably be the correct course of action, but eating the exceptions would be acceptable too i guess.
