### ISSUE TITLE
high CPU usage

### ISSUE THREAD

**Issue by gerbrent** [Mastermindzh/tidal-hifi#345]
Seeing today for the first time *very* high CPU usage

![image](https://github.com/Mastermindzh/tidal-hifi/assets/7018928/3f133fdb-d509-4f39-84d9-ca737729ba07)

### Current settings:

![image](https://github.com/Mastermindzh/tidal-hifi/assets/7018928/3c2584e8-ddeb-4894-b21c-800c47f529c0)

### system, version:

flatpak on NixOS

`flatpak list`:
   `TIDAL Hi-Fi     com.mastermindzh.tidal-hifi     5.8.0   stable  system`

### Context

Hard to say what initiated this state. Tidal has been open for 2 or so days, paused mid-song currently (REM Out of Time for your curiosity..).

**Comment by gerbrent** [comment]
Is there anything i can do to gather more helpful info when/if this happen again? Launch w some type of logging or...?

**Comment by Mastermindzh** [comment]
Hey,

If you launch it from the terminal the log will be output into the terminal itself 😄.
From what you show I can think of 1 or 2 things this can be:

1. Your CPU is doing the rasterization (e.g. GPU rendering), which can take a quick hit if it opens
2. Your system might be doing lots of file IO because of the notification/album update (this is fixed in [5.9.0](https://github.com/Mastermindzh/tidal-hifi/releases/tag/5.9.0)

I'd be interested if the logging brings something.


BTW: 
looking at your load averages seems to indicate that this is an infrequent occurrence. 
Your load average for the last 15 minutes was just under 4 cores (or +- 45%) for the entire system, you ram usage is also quite high indicating that you've got quite a few things open so a load average of 4 isn't entirely weird.

**Comment by gerbrent** [comment]
great insights! Will launch 5.8.0 with terminal until 5.9.0 hits flathub.

**Comment by gerbrent** [comment]
re load averages & additional context:

The high CPU usage was discovered by my laptop's cooling efforts spinning up to slightly-annoying levels, hence the investigation. Here are the load averages after quitting and restarting Tidal Hi-Fi, i.e. considerably lower, w very little other change to any other application (ram usage mostly from a browser tab addiction):



![image](https://github.com/Mastermindzh/tidal-hifi/assets/7018928/4406a040-218e-4e0b-a4e5-243fbd103d74)

**Comment by Mastermindzh** [comment]
5.9.0 will hit flathub tonight. Mar0Xy usually takes care of those but if she doesn't get to it by tonight then I will have a look myself 😄

**Comment by Mastermindzh** [comment]
@gerbrent how is the cpu usage?
For me it's been fine 😄

**Comment by gerbrent** [comment]
fine so far! But it's one of those intermittent issues... will keep an 👀  on it and report if it comes back!
