### ISSUE TITLE
login page wont load

### ISSUE THREAD

**Issue by Coosminn** [Mastermindzh/tidal-hifi#358]
Linux Mint 21.3 with a 6.5 kernel. The app opens but after pressing login button the webpage turns white and it will not load (even after 5 minutes)
![image](https://github.com/Mastermindzh/tidal-hifi/assets/52912877/3ad0be21-3f77-4bf2-abae-3b08f2773aea)
![image](https://github.com/Mastermindzh/tidal-hifi/assets/52912877/6a40415b-7874-4f10-a8a2-cc128e0cb85c)

**Comment by HK3212** [comment]
Also getting this issue on Ubuntu 22.04.4 LTS using either flatpak or AppImage. 

Using Snap install, it blocks me from logging in.

**Comment by Mastermindzh** [comment]
I installed mint in a VM and experienced no such issues.
You can try a few things:
- Remove cache (`~/.config/tidal-hifi` by default)
-  running it with `--no-sandbox` from the CLI.

**Comment by mr337** [comment]
I am getting the same issue. I believe if Tidal thinks you are a bot the app has an issue it goes to the white page. Similar to this page

![Selection_001](https://github.com/Mastermindzh/tidal-hifi/assets/413937/13852d82-df07-4869-b75f-8d0f96358c2f)


My solution
1. Run with the `--no-sandbox`, this seemed to allow the app to render that Bot check page and complete the verification
2. Login
3. Close app, and rerun without the `--no-sandbox` option
4. Enjoy the music

**Comment by articuno1au** [comment]
Cross-linking to #119
 
If you come across this issue with any of the various AUR versions

1. Remove `~/.config/tidal-hifi*`
2. Install `tidal-hifi-bin`
3. Run it with the `--no-sandbox` flag on the command line
4. Get past the bot screen and log in
5. Close the app
6. Run the app again without the `--no-sandbox` flag
7. You can then uninstall if you want to install a mod version or anything, otherwise enjoy.
