### ISSUE TITLE
Media player in KDE is buggy

### ISSUE THREAD

**Issue by sadorowo** [Mastermindzh/tidal-hifi#384]
![image](https://github.com/Mastermindzh/tidal-hifi/assets/97941280/27450d29-1cc2-42af-a364-82ee2d0a9333)
![image](https://github.com/Mastermindzh/tidal-hifi/assets/97941280/e9ce047d-6703-4c62-a98c-6b6c280d6061)

Song progress bar always stays at 0:00. When I try to seek the song from the player, the bar only changes position, but song isn't seeked at all. However, seeking in tidal-hifi works as it should.

App is minimized to menu bar.

My settings:
- notifications disabled
- hotkeys enabled
- api enabled + playback control enabled
- MPRIS integration enabled
- "Disable hardware built-in media keys" disabled

My setup:
```yaml
                   -`                    sadorowo@beast 
                  .o+`                   -------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Kernel: 6.8.7-arch1-1 
               `+oooooo:                 Uptime: 21 mins 
               -+oooooo+:                Packages: 885 (pacman) 
             `/:-:++oooo+:               Shell: zsh 5.9 
            `/++++/+++++++:              Resolution: 1920x1080 
           `/++++++++++++++:             DE: Plasma 6.0.4 
          `/+++ooooooooooooo/`           WM: kwin 
         ./ooosssso++osssssso+`          Theme: Breeze [GTK2/3] 
        .oossssso-````/ossssss+`         Icons: breeze [GTK2/3] 
       -osssssso.      :ssssssso.        Terminal: konsole 
      :osssssss/        osssso+++.       CPU: Intel i5-4590 (4) @ 3.700GHz 
     /ossssssss/        +ssssooo/-       GPU: AMD ATI Radeon RX 5500/5500M / Pro 5500M 
   `/ossssso+/:-        -:/+osssso+-     GPU: Intel HD Graphics 
  `+sso+:-`                 `.-/+oso:    Memory: 3729MiB / 15861MiB 
 `++:.                           `-/+/
 .`                                 `/                           
```

**Comment by hmm-star** [comment]
do i need to purchase a subscription to use this app or does this version gives premium access for free ?

**Comment by Mastermindzh** [comment]
Probably related to mpris not updating the played time, will attempt to investigate.

**Comment by thpar** [comment]
I have the same configuration as @sadorowo , but running the KDE Plasma spin of Fedora 39 (Plasma 5.27.11).

The communication with the KDE Media Player widget seems to be broken in following cases:
- Seeking, as mentioned above
- Pausing. Hitting the widget's pause button does stop the music, which is reflected in the Tidal app, but the KDE widget pretends to still be playing. Because of this, the play button is not showing while pausing, so you can't restart the music either without going to the app to hit its play button. This behaviour breaks system's play/pause hotkey in the same way.
- Scrolling on the media player icon is supposed to adjust Tidal's volume, but doesn't do anything.

Other functionality (next, previous, repeat and shuffle) seems to be working correctly.


Probably not directly related, but while the config says "Show tray icon", no Tidal tray icon is showing, only the one of the KDE Media Player.

**Comment by Shringe** [comment]
I think this may be related to my issue #387, especially if KDE media player also uses playerctl under the hood.

**Comment by thpar** [comment]
Update to 5.11.0 fixed the play/pause issue!

(Seeking and volume control not yet working)

**Comment by Mastermindzh** [comment]
Good to hear @thpar!

I haven't worked on volume control or seeking yet so that was expected 😄.

**Comment by thpar** [comment]
No problem and no rush. Just providing feedback as I didn't notice the commit. 
The pause button was the only feature I was really missing anyway. :slightly_smiling_face:

Thanks for your work!

**Comment by Mastermindzh** [comment]
Let's keep track of volume & seeking in the original issue 😄:

https://github.com/Mastermindzh/tidal-hifi/issues/199
