### ISSUE TITLE
App has two MPRIS interfaces

### ISSUE THREAD

**Issue by lilYozik** [Mastermindzh/tidal-hifi#400]
Hey, I've noticed that the app has two instances of the MPRIS interface. 
The first is the custom one that you implemented, and the second is called 'chromium'. I think it's probably the electron/chromium native implementation. 
From my testing with 'playerctl', it seems like the native implementation works better. It outputs paths to already cached album covers and it's handling changes of album names a lot smoother. At this point, it seems like the custom implementation is a bit redundant.

I'm using the tidal-hifi-bin 5.11.0-1 build from chaotic-aur.

![tidal-hifi-mpris](https://github.com/Mastermindzh/tidal-hifi/assets/151261928/c7bc44ba-810b-41b6-8b30-6be4786502ae)

**Comment by Mastermindzh** [comment]
Hey @lilYozik,

True, we offer a second one for people that don't want to use the chromium one or for desktop environments where the chromium one doesn't work as well (gnome is one of them)

You can disable the custom one in the settings fairly easily so it shouldn't be a problem if you prefer to use the chromium one.

Cool looking WM btw ❤️

**Comment by dionorgua** [comment]
I still think it's quite confusing to have two media interfaces that do mostly same thing. For me it was causing extra confusion because of behavior of `pause` command is different and I'm getting different behavior based on randomness (which one DE will use to control) (I created https://github.com/Mastermindzh/tidal-hifi/issues/800 for this)

It's possible to disable chromium built-in MPRIS for tidal-hifi using `--disable-features=HardwareMediaKeyHandling` arg
