### ISSUE TITLE
Arch Installation Fail

### ISSUE THREAD

**Issue by EvoXCX** [Mastermindzh/tidal-hifi#46]
Hey,

I have some problem to update tidal-hifi when I update it npm give me an error : 

npm ERR! semver.simplifyRange is not a function

I attach log to this issue

[2021-04-28T22_38_44_151Z-debug.log](https://github.com/Mastermindzh/tidal-hifi/files/6395237/2021-04-28T22_38_44_151Z-debug.log)

**Comment by Mastermindzh** [comment]
Hey @EvoXCX ,

This is a problem with your local NPM setup.
There are a few fixes..

## Least impactful
This won't change any of your system files, leaving the npm/semver install messed up but it will allow you to circumvent the error:

```sh
nvm use lts/erbium
# do whatever you were doing (like building tidal-hifi)
```

## fixing the npm install
By installing specific version of semver and then the new version of npm it will work well again.

```sh
sudo npm install -g semver@7.2.0
sudo npm install -g npm@7.7.0
# do whatever you were doing (like building tidal-hifi)
```

## most impactful
It's a rather harsh method but it works wonders....
```sh
rm -rf ~/.npm
npm clean cache --force
# do whatever you were doing (like building tidal-hifi)
```

**Comment by cabca** [comment]
Hello,

I have the same problem where the build is failing. I use YAY.
What I have seen is that the builder tries to build "tidal-hifi-2.2.0.pacman" goes to ./build/electron-builder.pacman.yml which ultimately send the script to /electron-builder.yml, but since the pacman file is disabled is fails and hence the whole process fails.
I don't know if my understanding is correct but if you can have a look I would really appreciate, I also attached  a screenshot.

![tidal-hifi fails to build](https://user-images.githubusercontent.com/73305198/117427248-85510280-af2d-11eb-90a4-d0e80b1c54af.png)
