### ISSUE TITLE
You have been blocked & a possible fix

### ISSUE THREAD

**Issue by dimitrisp2** [Mastermindzh/tidal-hifi#78]
So, I've been trying to get this to work on pop_os!, and I was getting a "You have been blocked" message, while in Firefox Tidal was working 100% ok.

I did some tests, and Tidal is probably blocking the user agent (includes tidal-hifi & electron in the string). I modified the src/main.js file as following:

I added "session" at the first line, as follows:
```const { app, BrowserWindow, globalShortcut, ipcMain, session } = require("electron");```

Then I went on and added the following lines:
```
session.defaultSession.webRequest.onBeforeSendHeaders((details, callback) => {
  details.requestHeaders['User-Agent'] = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36';
  callback({ cancel: false, requestHeaders: details.requestHeaders });
});
```

just above line 53:

```mainWindow.setMenuBarVisibility(store.get(settings.menuBar));```

Then tried to open it again, and it worked. I know the user agent shows Windows 10, I'm gonna try it with a different user agent and see how it goes.

**Comment by Mastermindzh** [comment]
We can keep this open, but spoofing the User-Agent would never be a default option.
If a lot of people experience this we can add a custom User-Agent override which would be opt-in.

**Comment by Elendilej** [comment]
I have the same problem. Elsewhere, I can easily log in (Windows 10, Android, web browser), but it doesn't work here in this modified application - I'm supposedly blocked (that's not true).  Please, how can I solve this?

**Comment by chrissnell-okta** [comment]
Hmmm.... I tried doing exactly as @dimitrisp2 suggested, but using the same real browser user-agent that I run my Tidal web player on.  No luck.  Still blocked.  I'm curious if this is actually sending the UA in *all* calls.  I wish I could get this thing running through a proxy like CharlesProxy to validate the correct headers.  

Perhaps Tidal has developed some new DRM feature that's blocking me?

**Comment by Mastermindzh** [comment]
@chrissnell,

That's the thing. It happens to random people at random times and it's never happened to me.
I don't mind supporting a configurable user-agent but it probably isn't the fix that we need.

I do suspect that Tidal blocks people because of "suspicious" behavior which might very well include the random user-agent.

**Comment by chrissnell** [comment]
I am not familiar with how tidal-hifi works but is it pulling the same
things from Tidal that their web player is?  In other words, is it
different/distinguishable from the web player?  I ask this because the web
player still functions on my end and tidal-hifi does not, despite forcing
tidal-hifi to use the identical user-agent.

I reached out to Tidal support who was completely useless and blamed it on
the SORBS blacklist (LOL).

**Comment by Mastermindzh** [comment]
@chrissnell ,

Tidal-hifi uses Electron (basically a chrome browser) to **open** listen.tidal.com.
The only things Tidal-hifi adds are:

- Preconfigured DRM support (which users don't always have in their browser)
- Shortcut support to mimick the desktop app (by **targetting & triggering** elements on the listen.tidal.com site, just like a user would)
- Some nifty content consumption stuff (like the discord integration, notifications, and the web API)

We haven't modified **any** of the user-agents so any website (including listen.tidal.com) can correctly identify this app as being **their** website loaded through Electron.

All that combined makes it pretty difficult to solve this in Tidal-Hifi. 
Some users have claimed updating the user-agent works but others (including you just now) claim it has no effect.

We shouldn't be spoofing anything to consume the website, which is why I'm reluctant to do it (as I stated previously, it would be an opt-in feature, not a default).

**Comment by kwiniarski97** [comment]
Would you try to install Chrome/Chromium browser? I've had exact same problem, as soon as I installed chromium fron Pop!_Shop I was able to log in inside the app.

**Comment by Mastermindzh** [comment]
Archived: https://github.com/Mastermindzh/tidal-hifi/wiki/Known-issues---workarounds#3-you-have-been-blocked-not-an-app-specific-problem
