### ISSUE TITLE
Opening fullscreen and leaving fullscreen enables UI menubar even when turned off

### ISSUE THREAD

**Issue by bjornpijnacker** [Mastermindzh/tidal-hifi#94]
Opening the fullscreen mode from the player and closing it with escape enables the menu bar even when the menubar is turned off in settings. Turning the menubar off requires going to the settings, then enabling and disabling the menubar. See attached video for more information (https://user-images.githubusercontent.com/35508080/148688503-789179d3-fc96-40ab-a945-1bf08c8963d3.mp4).

*Exact steps to reproduce:*
1. Open the now playing window by clicking the bottom bar or the arrow in the bottom right corner
2. In the top left, choose "Full Screen"
3. Close fullscreen mode by pressing Esc
4. The menu bar is now visible while it should not be.

**Comment by Mastermindzh** [comment]
Hey @bjornpijnacker,

I can easily recreate the issue. I don't know when I'll have the time to look into it but it is definitely a bug 😄.
Thanks!

**Comment by bjornpijnacker** [comment]
Thanks!

Just googling real quick makes it seem like this is a bug in Electron rather than tidal-hifi. A potential fix is shown here: https://github.com/jupyterlab/jupyterlab-desktop/commit/12819f95f7ebd8f0f155fdb618896f1cc353ef01, which is how jupyterlab fixed the issue.

**Comment by Mastermindzh** [comment]
Hey @bjornpijnacker, 

Yeah, I knew it was an electron issue since we don't do anything with fullscreen ourselves.
Funnily enough, the fix is nearly identical to the one I had in my mind 😂 (except variable names and I'd use the `store`).

Tell me, is this affecting your day to day usage? I think I can make some extra time tonight if this has any kind of priority 🤷🏻

**Comment by bjornpijnacker** [comment]
Hey!

It's not really affecting my day-to-day, as I don't use fullscreen all too often. In my opinion: no need to drop everything and fix it right away, it can wait until you have the time.

It's a small fix, luckily (:

**Comment by Mastermindzh** [comment]
Hey @bjornpijnacker,

The fix was a bit more elaborate (though not much..) because it isn't actually us (Tidal-hifi) that enables fullscreen but rather listen.tidal.com.

Because of that, I had to add an [event listener which triggered an event for the main process](https://github.com/Mastermindzh/tidal-hifi/commit/9412a9b19fa3f83c8b453a329d76c607a870a789#diff-032e180739c4103bc3c3e71de4e372ef41482cfedaf727481a9f0724a5763f5bR220-R222).

This event is listened to in the main process and it [updates the menubar to whatever setting the user has in their settings](https://github.com/Mastermindzh/tidal-hifi/commit/9412a9b19fa3f83c8b453a329d76c607a870a789#diff-27653c212e1cfe533e4eb2f7d0d3f89604c9de48a09583b4cbbbcbd08a07da79R36-R38).

Builds are now running. I expect a 2.7.1 release within the hour.

**Comment by Mastermindzh** [comment]
Released in [2.7.1](https://github.com/Mastermindzh/tidal-hifi/releases/tag/2.7.1)

**Comment by bjornpijnacker** [comment]
It works great, thanks!
